---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5fce67cf72c3b70016296f8e/webhook/forestry'
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: document
  path: content/blog/_index.md
  label: Blog
  templates:
  - blog
- type: document
  path: content/portfolio/_index.md
  label: Portfolio
  templates:
  - portfolio
- type: directory
  path: content
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
  - project
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.48'
